### ISSUE TITLE
setuptools version conflict between dependencies from cumulusci and metecho

### ISSUE THREAD

**Issue by RupertBarrow** [SFDO-Tooling/Metecho#1469]
I'm updating my Heroku installation of Metecho for the first time since several months.
Using Heroku build from my Metecho fork, I get this strange error : 
`-----> Installing pip 21.3.1, setuptools 57.5.0 and wheel 0.37.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
cumulusci 3.36.0 requires setuptools==57.0.0, but you have setuptools 57.5.0 which is incompatible.
`

Here is the whole build log : 
[build.log](https://github.com/SFDO-Tooling/Metecho/files/7490432/build.log)

**Comment by davisagli** [comment]
I think the appearance of this notice is a consequence of the Heroku Python buildpack updating to a more recent version of pip that is stricter about checking compatibility of the versions being installed. I see it in my Metecho instance as well; however it appears to be advisory only and didn't block installation.

@Br4nd0R the next time we update CumulusCI dependencies, let's try removing `--allow-unsafe` from the pip-compile commands so that setuptools doesn't get pinned to a specific version in CumulusCI's install requirements.
