### ISSUE TITLE
Bug - please upgrade to CumulusCI version 3.48.1 or later

### ISSUE THREAD

**Issue by RupertBarrow** [SFDO-Tooling/Metecho#1590]
On my personal install of Metecho, on Heroku, I received the following error message while trying to create a scratch org : 
`Uh oh. There was an error creating your new Scratch Org for Epic “My Epic.”
click.exceptions.UsageError: This project requires CumulusCI version 3.48.1 or later. To upgrade, please run this command: pip install --upgrade cumulusci `

Please upgrade Metecho to the latest version of Cumulus CI.

**Comment by davisagli** [comment]
This typically happens because when you generate a new cci project with `cci project init`, CumulusCI adds a `minimum_cumulusci_version` specification to cumulusci.yml with the current version. If you don't actually depend on changes in a recent version of CumulusCI, you can remove that line.

That said, we do intend to update the version of CumulusCI used by Metecho soon.

**Comment by RupertBarrow** [comment]
OK, understood.

But the current latest version is 3.48.2, whereas it is asking for 3.48.1 ...

**Comment by RupertBarrow** [comment]
@davisagli 
Just to confirm : your suggestion fixed my problem.
